services:
  postgres:
    image: postgres:15
    restart: always # 실행을 할때마다 재시작
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: one_for_all
